ALTER TABLE chat_admins
    ADD COLUMN IF NOT EXISTS can_verify  BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS can_keyword BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS can_points  BOOLEAN NOT NULL DEFAULT FALSE;
